export {
  auditM3aOfflineDesign,
  blindM3a1IntegrityAudit,
  type M3a1Arm,
  type M3a1ArmMetrics,
  type M3a1AuditIssue,
  type M3a1BlindAuditCounts,
  type M3a1OfflineAuditReport,
  type M3a1Sources,
} from "./audit.js";
export {
  type EvidenceCitation,
  evidenceCitationSchema,
  type EvidenceContext,
  evidenceContextFitsQuery,
  evidenceContextSchema,
  type EvidenceContextUsage,
  evidenceContextUsageSchema,
  type EvidenceEdge,
  evidenceEdgeSchema,
  type EvidenceEncoding,
  evidenceEncodingSchema,
  type EvidenceFact,
  evidenceFactSchema,
  type EvidenceNeighborhood,
  evidenceNeighborhoodSchema,
  type EvidencePath,
  evidencePathSchema,
  type EvidenceQuery,
  evidenceQuerySchema,
  type EvidenceRelationship,
  evidenceRelationshipSchema,
  type EvidenceSelectionKind,
  type EvidenceSelectionReference,
  evidenceSelectionReferenceSchema,
  type EvidenceSource,
  type EvidenceSourceFailure,
  evidenceSourceFailureSchema,
  type EvidenceSourceIdentity,
  evidenceSourceIdentitySchema,
  isEvidenceFactBelievedAt,
  measureEvidenceContext,
  referenceEvidenceSelection,
  selectEvidence,
} from "./contract.js";
export {
  M3A1_CORPUS_PROTOCOL,
  M3A1_PREREGISTERED_CORPUS,
  M3A1_REFERENCE_GRAPH,
  type M3a1Category,
  m3a1CategorySchema,
  type M3a1Split,
  m3a1SplitSchema,
  type M3aTask,
  m3aTaskSchema,
} from "./corpus.js";
export { M3A1_FACTORIAL_ARMS, M3A1_PROSPECTIVE_ANALYSIS } from "./design.js";
export {
  createGraphSelectedAdjacencyEvidenceSource,
  createGraphSelectedFactsEvidenceSource,
  createInMemoryGraphEvidenceSource,
  type EvidenceGraph,
  evidenceGraphSchema,
} from "./graph.js";
export {
  createMatchedTextChunks,
  createMatchedTextEvidenceSource,
  type TextEvidenceChunk,
  textEvidenceChunkSchema,
} from "./text.js";
