export {
  auditM3aOfflineDesign,
  blindM3a1IntegrityAudit,
  type M3a1Arm,
  type M3a1ArmMetrics,
  type M3a1AuditIssue,
  type M3a1BlindAuditCounts,
  type M3a1OfflineAuditReport,
  type M3a1Sources,
} from "./audit.js";
export {
  type EvidenceCitation,
  evidenceCitationSchema,
  type EvidenceContext,
  evidenceContextFitsQuery,
  evidenceContextSchema,
  type EvidenceContextUsage,
  evidenceContextUsageSchema,
  type EvidenceEdge,
  evidenceEdgeSchema,
  type EvidenceEncoding,
  evidenceEncodingSchema,
  type EvidenceFact,
  evidenceFactSchema,
  type EvidenceNeighborhood,
  evidenceNeighborhoodSchema,
  type EvidencePath,
  evidencePathSchema,
  type EvidenceQuery,
  evidenceQuerySchema,
  type EvidenceRelationship,
  evidenceRelationshipSchema,
  type EvidenceSelectionKind,
  type EvidenceSelectionReference,
  evidenceSelectionReferenceSchema,
  type EvidenceSource,
  type EvidenceSourceFailure,
  evidenceSourceFailureSchema,
  type EvidenceSourceIdentity,
  evidenceSourceIdentitySchema,
  isEvidenceFactBelievedAt,
  measureEvidenceContext,
  referenceEvidenceSelection,
  selectEvidence,
} from "./contract.js";
export {
  M3A1_CORPUS_PROTOCOL,
  M3A1_PREREGISTERED_CORPUS,
  M3A1_REFERENCE_GRAPH,
  type M3a1Category,
  m3a1CategorySchema,
  type M3a1Split,
  m3a1SplitSchema,
  type M3aTask,
  m3aTaskSchema,
} from "./corpus.js";
export { M3A1_FACTORIAL_ARMS, M3A1_PROSPECTIVE_ANALYSIS } from "./design.js";
export {
  createGraphSelectedAdjacencyEvidenceSource,
  createGraphSelectedFactsEvidenceSource,
  createInMemoryGraphEvidenceSource,
  type EvidenceGraph,
  evidenceGraphSchema,
} from "./graph.js";
export {
  blindAuditM3bMaterialization,
  createDeterministicM3bOracle,
  createM3bSharedPlan,
  createMemoryM3bStore,
  type DeterministicM3bOracle,
  M3B_ORACLE_MODELS,
  M3B_ORACLE_PROMPT,
  M3B_TRANSPORT_RETRY_POLICY,
  type M3bBlindAuditCounts,
  type M3bFrozenCase,
  type M3bManifest,
  type M3bMaterializedPhase,
  type M3bOracle,
  type M3bOracleAttempt,
  type M3bOracleFailureCode,
  type M3bOracleIdentity,
  type M3bOracleOutput,
  m3bOracleOutputSchema,
  type M3bOracleRequest,
  m3bOracleRequestSchema,
  type M3bPhase,
  type M3bRecord,
  type M3bRunResult,
  type M3bSharedPlan,
  type M3bStore,
  materializeM3bPhase,
  runM3bWithOracles,
  validateM3bMaterialization,
} from "./m3b.js";
export {
  loadM3bPhaseCases,
  M3B_CORPUS_PROTOCOL,
  M3B_PREREGISTERED_CORPUS,
  M3B_REFERENCE_GRAPH,
} from "./m3b-corpus.js";
export {
  auditM3bWilliamsSchedule,
  createM3bWilliamsSchedule,
  M3B_WILLIAMS_SEQUENCES,
  type M3bArm,
  m3bArmSchema,
  type M3bScheduleAudit,
  type M3bScheduleEntry,
  type M3bWilliamsSchedule,
  m3bWilliamsScheduleSchema,
} from "./m3b-schedule.js";
export {
  calculateM3bPairedInterval,
  evaluateM3bStatistics,
  M3B_CONTRASTS,
  M3B_MULTIPLICITY_POLICY,
  type M3bContrastEstimand,
  type M3bContrastId,
  type M3bContrastReport,
  type M3bPairedInterval,
  type M3bStatisticalObservation,
  type M3bStatisticalReport,
} from "./m3b-statistics.js";
export {
  createMatchedTextChunks,
  createMatchedTextEvidenceSource,
  type TextEvidenceChunk,
  textEvidenceChunkSchema,
} from "./text.js";
