export {
  type BenchmarkBudgetController,
  type BenchmarkBudgetReservation,
  type BenchmarkBudgetSettlement,
  type BenchmarkCaseRecord,
  benchmarkCaseRecordSchema,
  type BenchmarkMethod,
  benchmarkMethodIdentity,
  type BenchmarkRecordCoordinate,
  type BenchmarkRecordCoordinator,
  type BenchmarkRepairTrialInput,
  type BenchmarkRunInput,
  type BenchmarkRunResult,
  type BenchmarkScore,
  benchmarkScoreSchema,
  type BenchmarkStore,
  type BenchmarkSummary,
  type CatalogResolver,
  type ConfidenceInterval,
  createInMemoryBenchmarkStore,
  evaluateResearchGates,
  type HiddenEvaluationScore,
  type RateEstimate,
  type ResearchGate,
  runBenchmark,
  scoreGeneration,
  summarizeBenchmark,
} from "./benchmark.js";
export {
  type DeterministicEffect,
  deterministicEffectSchema,
  type Example,
  exampleSchema,
  freezePlanGenerationCase,
  type FrozenPlanGenerationCase,
  type HiddenEvaluation,
  hiddenEvaluationSchema,
  type InfeasibilityWitness,
  type InfeasibilityWitnessInput,
  infeasibilityWitnessSchema,
  type PlanGenerationCase,
  planGenerationCaseSchema,
  type PlanProperty,
  planPropertySchema,
  toPublicExamples,
} from "./case.js";
export {
  type CatalogConformanceFixture,
  catalogConformanceFixtureSchema,
  type CatalogConformanceReport,
  catalogConformanceReportSchema,
  type CatalogConformanceSuite,
  catalogConformanceSuiteSchema,
  conformCatalogsOffline,
  verifyCatalogConformanceReport,
} from "./catalog-conformance.js";
export {
  type CatalogConformanceDiagnostic,
  catalogConformanceDiagnosticSchema,
  type CatalogDiagnosticAssessment,
  catalogDiagnosticAssessmentSchema,
  type CatalogDiagnosticCode,
  catalogDiagnosticCodeSchema,
  type CatalogDiagnosticOutcome,
  catalogDiagnosticOutcomeSchema,
  type CatalogRepairAction,
  catalogRepairActionSchema,
  diagnoseCatalogsOffline,
  renderCatalogConformanceDiagnostic,
  verifyCatalogConformanceDiagnostic,
} from "./catalog-diagnostic.js";
export {
  CODEMODE_MODEL_VISIBLE_GRAMMAR_CONTRACT,
  CODEMODE_PROTOCOL,
  type CodeModeArtifact,
  type CodeModeArtifactSummary,
  type CodeModeCapabilityMethod,
  type CodeModeEffectHandler,
  type CodeModeEffectRequest,
  type CodeModeEffectResult,
  type CodeModeExecutionFailure,
  type CodeModeExecutionResult,
  type CodeModeRuntimeUsage,
  type CodeModeStaticAnalysis,
  compileCodeMode,
  type CompileCodeModeInput,
  executeCodeMode,
  type ExecuteCodeModeOptions,
  inspectCodeModeArtifact,
  validateCodeModeSourceSyntax,
} from "./codemode.js";
export {
  type CodeModeAttemptRecord,
  type CodeModeGenerationRecord,
  codeModeGenerationRecordSchema,
  type CodeModeGenerationSession,
  type CodeModeGenerationStrategy,
  type CodeModeInitialRequest,
  type CodeModeModelAdapter,
  type CodeModeModelRequest,
  type CodeModeOutcome,
  codeModeOutcomeSchema,
  type CodeModeRepairRequest,
  compileCodeModeStructuredOutputTransport,
  generateCodeMode,
  type GenerateCodeModeInput,
  M2_CODEMODE_PROMPT_PROTOCOL,
} from "./codemode-model.js";
export {
  createM1aCatalogResolver,
  loadM1aCorpus,
  M1A_CATALOG_IDS,
  M1A_HOLDOUTS,
  M1A_WORKFLOW_MAX_ITERATIONS,
  M1A_WORKFLOW_VERSION,
  type M1aCorpusPartition,
  partitionM1aCorpus,
} from "./corpus.js";
export {
  type BenchmarkSplit,
  benchmarkSplitSchema,
  createExperimentManifest,
  type ExperimentCaps,
  type ExperimentManifest,
  type ExperimentManifestInput,
  experimentManifestSchema,
  type ExperimentMethod,
  type ExperimentMethodInput,
  type ExperimentRepairTrial,
  experimentRepairTrialSchema,
  type ExperimentTransportSchemaBinding,
  type ExperimentVersions,
  verifyExperimentManifest,
} from "./experiment.js";
export { loadM1aRecordedFixtures, RECORDED_DOUBLE_PLAN } from "./fixtures.js";
export {
  assertNoM1bHeldOutReuse,
  loadM1cPreregisteredCorpus,
  M1C_CORPUS_PROTOCOL,
  type M1cPreregisteredCorpus,
} from "./m1c-corpus.js";
export {
  createInMemoryM2CodeModeStore,
  createM2CounterbalancedSchedule,
  createM2CounterbalancedScheduleFromIdentity,
  createM2PairedExperimentDigest,
  createM2PairedExperimentDigestFromIdentity,
  M2_COMPARISON_PROTOCOL,
  M2_SUPERSEDED_M21_IDENTITIES,
  M2_SUPERSEDED_M22_IDENTITIES,
  type M2CodeModeMethod,
  type M2CodeModeMethodIdentity,
  type M2CodeModeRecord,
  m2CodeModeRecordSchema,
  type M2CodeModeRunInput,
  type M2CodeModeRunResult,
  type M2CodeModeScore,
  type M2CodeModeStore,
  type M2CounterbalancedSchedule,
  m2CounterbalancedScheduleSchema,
  type M2MatchedRecord,
  type M2PairedRunInput,
  type M2PairedRunResult,
  type M2Representation,
  type M2ResourceComparison,
  type M2ScheduleEntry,
  matchM2PairedRecords,
  runM2CodeModeBenchmark,
  runM2PairedBenchmark,
} from "./m2-benchmark.js";
export {
  assertM2CorpusNamespaceDisjoint,
  blindM2HeldOutIntegrityAudit,
  createM2CatalogResolver,
  loadM2PreregisteredCorpus,
  M2_CORPUS_PROTOCOL,
  type M2BlindAuditCounts,
  type M2PreregisteredCorpus,
} from "./m2-corpus.js";
export {
  calculateM2PairedRiskDifferenceInterval,
  evaluateM2PairedStatistics,
  M2_PAIRED_ANALYSIS_PLAN,
  type M2BinaryPairReport,
  type M2NonInferiorityReport,
  type M2PairedContinuousReport,
  type M2PairedRiskDifferenceInterval,
  type M2PairedStatisticalReport,
  type M2ProspectiveGateResult,
  type M2ProviderStratumReport,
  type M2RepetitionStatisticalReport,
} from "./m2-statistics.js";
export {
  auditM6FalseEquivalence,
  loadM6OfflineStrategyCorpus,
  type M6FalseEquivalenceAudit,
  type M6OfflineStrategyCorpus,
} from "./m6-corpus.js";
export {
  auditM6cFalseEquivalence,
  loadM6cOfflineConformanceCorpus,
  type M6cFalseEquivalenceAudit,
  type M6cOfflineConformanceCorpus,
} from "./m6c-corpus.js";
export {
  assignM6dSequence,
  auditM6dWorkloadDisjointness,
  boundM6dMaximumCost,
  designM6dPairedStudy,
  type M6dBound,
  m6dBoundSchema,
  type M6dDisjointnessAudit,
  type M6dMaximumCostBound,
  type M6dStudyDesign,
  m6dStudyDesignSchema,
  type M6dWorkloadIdentity,
  m6dWorkloadIdentitySchema,
  verifyM6dStudyDesign,
} from "./m6d-design.js";
export {
  type AdapterDispatchEvidence,
  DEFAULT_INFERENCE_SETTINGS,
  type GenerationConstraint,
  type GenerationOutcome,
  generationOutcomeSchema,
  type GenerationStrategy,
  type InferenceSettings,
  inferenceSettingsSchema,
  type InitialGenerationRequest,
  M1A_GENERATION_STRATEGIES,
  MAX_REPAIR_ATTEMPTS,
  type ModelAdapter,
  type ModelAdapterFailure,
  type ModelIdentity,
  type ModelRequest,
  type ModelResponse,
  type ModelResponseMetadata,
  type ModelUsage,
  type PublicExample,
  type RepairGenerationRequest,
  type TaskInput,
  taskInputBoundSchema,
  taskInputSchema,
  type UnplannableWitness,
  type UnplannableWitnessInput,
  unplannableWitnessSchema,
} from "./model.js";
export {
  type AttemptPhase,
  compileModelPlanProposal,
  generatePlan,
  type GeneratePlanInput,
  type GenerationSession,
} from "./pipeline.js";
export {
  calculateCostUsdMicros,
  calculateMaximumCostUsdMicros,
  createPricingSnapshot,
  type PricingEntry,
  pricingEntrySchema,
  type PricingSnapshot,
  type PricingSnapshotInput,
  pricingSnapshotSchema,
  verifyPricingSnapshot,
} from "./pricing.js";
export {
  createRecordedModelAdapter,
  freezeRecordedModelFixture,
  type FrozenRecordedModelFixture,
  modelIdentityKey,
  type RecordedModelAdapter,
  type RecordedModelFixture,
  recordedModelFixtureSchema,
} from "./recorded-adapter.js";
export {
  type AttemptRecord,
  attemptRecordSchema,
  diagnosticRecordSchema,
  type GenerationFinalKind,
  type GenerationRecord,
  generationRecordSchema,
  generationStrategySchema,
  modelIdentitySchema,
  modelUsageSchema,
} from "./records.js";
export {
  applyDeterministicPlanMutation,
  type DeterministicPlanMutation,
  type DeterministicPlanMutationInput,
  deterministicPlanMutationSchema,
  prepareSharedRepairTrial,
  type SharedRepairTrial,
} from "./repair-benchmark.js";
export {
  bindStrategyTemplate,
  type BoundStrategy,
  compileTemplateFirst,
  createStrategyRegistry,
  createStrategyTemplate,
  type ExactStrategyInstantiationHash,
  exactStrategyInstantiationHashSchema,
  inspectStrategyRegistry,
  matchStrategyTemplate,
  mineStrategyTraces,
  type NormalizedStrategyPlan,
  normalizeSuccessfulStrategyPlan,
  type OfflinePlanner,
  type OracleObservationContract,
  oracleObservationContractSchema,
  type PlanSkeleton,
  planSkeletonSchema,
  type PublicTaskClass,
  publicTaskClassSchema,
  registerStrategyTemplate,
  type SanitizedStrategyTrace,
  sanitizedStrategyTraceSchema,
  type StrategyBindingFailure,
  type StrategyContractHash,
  strategyContractHashSchema,
  type StrategyLifecycleEvent,
  type StrategyLifecycleEventHash,
  strategyLifecycleEventHashSchema,
  strategyLifecycleEventSchema,
  type StrategyLifecycleStatus,
  strategyLifecycleStatusSchema,
  type StrategyMatch,
  type StrategyParameterBinding,
  type StrategyParameterSlot,
  strategyParameterSlotSchema,
  type StrategyPromotionEvidence,
  strategyPromotionEvidenceSchema,
  type StrategyPublicTaskFeatures,
  type StrategyRegistry,
  type StrategyTemplate,
  type StrategyTemplateHash,
  strategyTemplateHashSchema,
  strategyTemplateSchema,
  type StrategyTraceMiningReport,
  type StrategyValidationEnvelope,
  strategyValidationEnvelopeSchema,
  type TemplateFirstCompilation,
  type TrajectoryShapeHash,
  trajectoryShapeHashSchema,
  transitionStrategyTemplate,
  verifyStrategyTemplate,
} from "./strategy.js";
export {
  type CaseStructuredOutputTransport,
  compileCaseStructuredOutputTransports,
  compileStructuredOutputTransport,
  normalizeStructuredOutputEnvelope,
  PORTABLE_TRANSPORT_COMPILER_VERSION,
  type StructuredOutputCatalogResolver,
  type StructuredOutputTransport,
  structuredOutputTransportSchema,
  SUPPORTED_PORTABLE_TRANSPORT_COMPILER_VERSIONS,
  validatePortableStructuredOutputSchema,
} from "./transport.js";
export {
  blindPlanGenerationValidityAudit,
  createReferencePlanWitness,
  validatePlanGenerationCases,
} from "./validity.js";
export { validateUnplannableWitness } from "./witness.js";
